# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Scrap book title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='scrapbooks.ScrapBook')),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='scraps.Scrap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
